layout_spectrum: 0.701603377237916
typography_spectrum: 0.9487814430613071
color:
  brandColors:
    - '#1e2d3f'
    - '#ffffff'
    - '#cfd2d6'
    - '#a0a6ae'
    - '#767e88'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-49652141-1
  facebook: null
  twitter: null
author:
  name: Innovaize
  email: info@innovaize.com
  url: www.innovaize.com
name: INNOVAIZE
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: INNOVAIZE
description: Inteligencia Progresiva
purpose: []
