name: INNOVAIZE
favicon: null
layout_spectrum: 0.86128
typography_spectrum: 0.53142
title: Inteligencia Progresiva
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-49652141-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#038390'
    - '#5b9ab9'
    - '#28272f'
    - '#4f525d'
  brandStrength: 0.7223416
  lightness: 0.5
  saturation: 0.7840185076929629
  rhythmicContrast: 0.25
purpose: []
