name: INNOVAIZE
favicon: null
layout_spectrum: 0.60271
typography_spectrum: 0.761012673843652
title: Inteligencia Progresiva
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8617843352258205
  lightness: 0.9338183619547635
  saturation: 0.7840185076929629
  rhythmicContrast: 0.9904008158482611
purpose: []
